# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.FoCUS <- function(dataGen, thres, mu0, grid, K) {
    .Call(`_projetAlgo_FOCuS`, dataGen, thres, mu0, grid, K)
}

